language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: brainstorming-nodejs
  api_key:
    secure: Hs+6/vNMsPEq+zegA+ltqwA1jHYq53Pn5Xs1rswJ+VBYTubXCrsFF4ssySKCurEZvwoF6xNep9hPaTTiXRD6cECIckjpIlot7TVc3Y7NnUmRdOcgPw7zYsdN+rlqXAY2X/jLCEeKnT0aZ03DJJGd4myXkq2ElFAcC8GZN99Ex+DbNecYuNmXQdjFp/vlO4gwiFnZtBN+CXYj2qk93Tobj3+zWiDiuC9LvXs2VigqYjKIreNL9yN9fo9XwtXntp422VUAlPkbIpMVvws0Es36YcaFpmal9xXSSzDFYLpXw5wg3oq2FL0sCWI1NyQUlaWCj8496eUWNfWTb8phcLhPcorNYs5TR3uPRWR1BQD8h99Mod5gbDU1isSl1phPwBM16BDVnnPj9+1/JK36tROigbv7wd2i2dUkHLa9A6qQ0G0TtMnlyXbiFV+VbYNKa0aJ2aXyK5IqR4kEuDV5ME8C31IgBQk4lw2IByF22YCAauK3SSMDMTuDQknseWr9eXYLOSEAOeW0HSOL5YdZLvwmYDLcbTauLuudzPYp+CpCaXmmHONP23pkIUUoRbtlwtEvFMIMTCk0L8GjVWC5GQm+ZpA3rOixgn6PSQKJfUThkRG8NNJMGXEfGR54ei6gQ/0gyZ2MjB8WciwIlGr+s50JqonCeajE8vHhMvG/gudJPkQ=
